web:
  build: ./
  dockerfile: ./docker/nginx/Dockerfile
  volumes:
    - ./:/var/www
  ports:
    - "3000:80"
  links:
    - app

app:
  build: ./
  dockerfile: ./docker/app/Dockerfile
  volumes:
    - ./apiservice/:/var/www
  links:
    - rabbit

userservice:
  build: ./
  dockerfile: ./docker/userservice/Dockerfile
  volumes:
    - ./userservice/:/var/userservice
  links:
    - rabbit
    - mysqldb

rabbit:
  hostname: rabbit
  image: rabbitmq:latest
  environment:
    - RABBITMQ_DEFAULT_USER=admin
    - RABBITMQ_DEFAULT_PASS=mypass
  ports:
    - "8051:4369"
    - "8052:5671"
    - "8053:5672"
    - "8054:25672"

mysqldb:
    image: mysql:5.6
    ports:
        - "3306:3306"
    volumes:
        - ./docker/mysqldb/data:/var/lib/mysql
        - ./docker/mysql/:/docker-entrypoint-initdb.d
    environment:
        MYSQL_DATABASE: userservice
        MYSQL_USER: userservice
        MYSQL_PASSWORD: password
        MYSQL_ROOT_PASSWORD: root
